name: Release one platform to RubyGems

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag name to release (e.g., v0.2.0)"
        required: true
        type: string
      platform:
        description: "GEM_PLATFORM to release"
        required: true
        type: choice
        options:
          - x86_64-linux
          - aarch64-linux
          - x86_64-darwin
          - arm64-darwin
          - x64-mingw32
          - x64-mingw-ucrt

jobs:
  push-one:
    environment: release-rubygems
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            ruby-version: "3.4"
            gem_platform: x86_64-linux
          - os: ubuntu-24.04-arm
            ruby-version: "3.4"
            gem_platform: aarch64-linux
          - os: macos-13 # Intel
            ruby-version: "3.4"
            gem_platform: x86_64-darwin
          - os: macos-14 # Apple Silicon
            ruby-version: "3.4"
            gem_platform: arm64-darwin
          - os: windows-latest
            ruby-version: "2.7" # Ruby 2.7 is used for x64-mingw32
            gem_platform: x64-mingw32
          - os: windows-latest
            ruby-version: "3.4"
            gem_platform: x64-mingw-ucrt

    runs-on: ${{ matrix.os }}

    permissions:
      id-token: write # for trusted publishing
      contents: write # for tag/contents access if needed

    env:
      GEM_PLATFORM: ${{ matrix.gem_platform }}

    steps:
      - name: Checkout tag
        if: ${{ matrix.gem_platform == inputs.platform }}
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          ref: refs/tags/${{ inputs.tag }}

      - name: Set up Ruby
        if: ${{ matrix.gem_platform == inputs.platform }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Show versions
        if: ${{ matrix.gem_platform == inputs.platform }}
        run: |
          ruby -v
          gem -v
          bundle -v
        shell: bash

      - name: Update RubyGems for Windows Ruby 2.7 (enable 'gem exec')
        if: ${{ matrix.gem_platform == 'x64-mingw32' && matrix.gem_platform == inputs.platform }}
        run: |
          gem update --system 3.4.22
          gem --version
        shell: bash

      - name: Prepare vendored binary (bundle exec rake vendor:auto)
        if: ${{ matrix.gem_platform == inputs.platform }}
        run: |
          bundle exec rake vendor:auto
        shell: bash

      - name: Release gem to RubyGems.org
        if: ${{ matrix.gem_platform == inputs.platform }}
        uses: rubygems/release-gem@v1
